name: 01 - Building Blocks v1 - Piotr Koska szkolenie

on:
  push:
    branches: [feature/cw01]
  workflow_dispatch:

jobs:
  echo-hello:
    name: "Hello"
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello, World!"
          sleep 10

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "I will fail"
          exit 1  # dowolny kod != 0 spowoduje błąd kroku
      - name: Say goodbye
        run: echo "Goodbye!"

  trzeci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show conteiner
        run: |
          docker ps -a
          python --version
          apt install htop -y
        # Dodaj inne kroki i zobacz jak zachowuje sie github actions jako osobne joby oraz kroki w tym jobie.
