name: 04 - Workflow uses actions

on:
  workflow_dispatch:

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Use actions/checkout action
        uses: actions/checkout@v3
      - name: Pokaz zawarto≈õ katalogu roboczego
        run: ls -la
